pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -f log-microsservico/pom.xml -DoutputDirectory=~/log -B -DskipTests clean package'
                
            }
        }
        stage('Deploy') { 
            steps {
				// sh 'PM2_HOME=\'/home/ubuntu/.pm2\' pm2 delete log'
            	dir('/home/ubuntu') {
            		echo 'Destruindo instancia atual'
            		sh 'log-microsservico/destroyLogInstance.sh'
            		echo 'Instancia destruida com sucesso'
            		
            		echo 'Deletando .jar antigo'
            		sh 'log-microsservico/removeLogJar.sh'
            		echo 'Jar deletado com sucesso'
            		
            		echo 'Copiando .jar novo para pasta definitiva'
            		sh 'cp /var/lib/jenkins/workspace/log/log-microsservico/target/log-microsservico*.jar /home/ubuntu/log-microsservico/log-microsservico.jar'
            		echo 'Jar copiado com sucesso'
            		
            		echo 'Subindo instancia nova'
					sh 'log-microsservico/runLog.sh'
					echo 'Instancia nova executada com sucesso'
				}
            }
        }
    }
    // post {
	//	success {
	//		echo 'Esteira finalizada com sucesso!'
     //   }
	//	failure {
	//		echo 'Esteira falhou...'
     //   }
    // }
}
